### ISSUE TITLE
[GENERAL] Error "Need service name for --build-arg option" after docker-compose

### ISSUE THREAD

**Issue by llnk** [immuni-app/immuni-backend-exposure-ingestion#20]
# Issue content
After running the docker compose command as described in the documentation I get the following error: Need service name for --build-arg option, command below:

```
test@test-VirtualBox:~/immuni/immuni-backend-exposure-ingestion/docker$ docker-compose build     --build-arg GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)     --build-arg GIT_SHA=$(git rev-parse --verify HEAD)     --build-arg GIT_TAG=$(git tag --points-at HEAD | cat)     --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
ERROR: Need service name for --build-arg option
```

Docker version:
```
test@test-VirtualBox:~/immuni/immuni-backend-exposure-ingestion/docker$ sudo docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

```

**Comment by ocardia** [comment]
Hey @llnk, I did run it right now by copy-pasting what you posted (although it looks exactly as instructed in the doc), and I succeed in building it.

What's your `docker-compose` version? I see `docker-compose version 1.25.5, build 8a1c60f6` on my side.

Also, sanity check: did you do any change or was it a fresh, just pulled repo?

Eventually, consider that even the CI is running the same exact command, thus some more details on how to reproduce your issue would be great! Keep us posted!

**Comment by llnk** [comment]
Hi Ocardia,
to give more context: I am with a fresh & clean installation of Ubuntu 18.04 virtualized with Virtual Box (on Windows 10 but I don't the host OS matters much).

Before installing the stuff I run 

`apt-get update && apt-get upgrade`

After that I just cloned the repo and run the docker cmd.

Regarding the version of docker-compose, please see the output:

```
test@test-VirtualBox:~/immuni/immuni-backend-exposure-ingestion/docker$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```
And that maybe is interesting since I see that I am on version 1.17 while you are on 1.25...

**Comment by llnk** [comment]
Ok so I think I have figured out what happened.
If you install docker-compose with apt-get on Ubuntu 18 (IDK if it happens also on Ubuntu 20), apt will install docker compose version 1.17: and your command fails with this version.

To solve the issue I had to remove docker compose, and install it from docker directly with `curl`. Now I am with version 1.26 and it works fine.

Maybe it's better to specify that docker-compose must be installed with curl and not with apt-get

**Comment by ocardia** [comment]
Hey @llnk, I'm glad you managed to get it working!

I do agree adding this note to the docs would be helpful for others too. Let me re-open the issue so as to track this documentation enhancement.

It's a small change, hopefully it could be squeezed in soon enough.

Thanks.
